version: '3'
services:
  jupyter:
    network_mode: bridge
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./my_notebook.ipynb:/app/my_notebook.ipynb
    environment:
      - PYTHONPATH=/app
